/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calc;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }
    Double v1, v2;
    String sinal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtArea = new javax.swing.JTextField();
        btnNum0 = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnPorcent = new javax.swing.JButton();
        btnEleva = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnVezes = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnSoma = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        txtArea.setBackground(new java.awt.Color(0, 0, 0));
        txtArea.setForeground(new java.awt.Color(0, 0, 0));
        txtArea.setEnabled(false);

        btnNum0.setBackground(new java.awt.Color(255, 255, 255));
        btnNum0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum0.setForeground(new java.awt.Color(255, 255, 255));
        btnNum0.setText("0");
        btnNum0.setAutoscrolls(true);
        btnNum0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum0.setContentAreaFilled(false);
        btnNum0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum0.setFocusPainted(false);
        btnNum0.setVerifyInputWhenFocusTarget(false);
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });

        btnNum1.setBackground(new java.awt.Color(255, 255, 255));
        btnNum1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum1.setForeground(new java.awt.Color(255, 255, 255));
        btnNum1.setText("1");
        btnNum1.setAutoscrolls(true);
        btnNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum1.setContentAreaFilled(false);
        btnNum1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum1.setFocusPainted(false);
        btnNum1.setVerifyInputWhenFocusTarget(false);
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });

        btnNum2.setBackground(new java.awt.Color(255, 255, 255));
        btnNum2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum2.setForeground(new java.awt.Color(255, 255, 255));
        btnNum2.setText("2");
        btnNum2.setAutoscrolls(true);
        btnNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum2.setContentAreaFilled(false);
        btnNum2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum2.setFocusPainted(false);
        btnNum2.setVerifyInputWhenFocusTarget(false);
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnNum3.setBackground(new java.awt.Color(255, 255, 255));
        btnNum3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum3.setForeground(new java.awt.Color(255, 255, 255));
        btnNum3.setText("3");
        btnNum3.setAutoscrolls(true);
        btnNum3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum3.setContentAreaFilled(false);
        btnNum3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum3.setFocusPainted(false);
        btnNum3.setInheritsPopupMenu(true);
        btnNum3.setVerifyInputWhenFocusTarget(false);
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnNum4.setBackground(new java.awt.Color(255, 255, 255));
        btnNum4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum4.setForeground(new java.awt.Color(255, 255, 255));
        btnNum4.setText("4");
        btnNum4.setAutoscrolls(true);
        btnNum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum4.setContentAreaFilled(false);
        btnNum4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum4.setFocusPainted(false);
        btnNum4.setVerifyInputWhenFocusTarget(false);
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });

        btnNum5.setBackground(new java.awt.Color(255, 255, 255));
        btnNum5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum5.setForeground(new java.awt.Color(255, 255, 255));
        btnNum5.setText("5");
        btnNum5.setAutoscrolls(true);
        btnNum5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum5.setContentAreaFilled(false);
        btnNum5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum5.setFocusPainted(false);
        btnNum5.setVerifyInputWhenFocusTarget(false);
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });

        btnNum6.setBackground(new java.awt.Color(255, 255, 255));
        btnNum6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum6.setForeground(new java.awt.Color(255, 255, 255));
        btnNum6.setText("6");
        btnNum6.setAutoscrolls(true);
        btnNum6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum6.setContentAreaFilled(false);
        btnNum6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnNum6.setVerifyInputWhenFocusTarget(false);
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });

        btnNum7.setBackground(new java.awt.Color(255, 255, 255));
        btnNum7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum7.setForeground(new java.awt.Color(255, 255, 255));
        btnNum7.setText("7");
        btnNum7.setAutoscrolls(true);
        btnNum7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum7.setContentAreaFilled(false);
        btnNum7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum7.setFocusPainted(false);
        btnNum7.setVerifyInputWhenFocusTarget(false);
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum8.setBackground(new java.awt.Color(255, 255, 255));
        btnNum8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum8.setForeground(new java.awt.Color(255, 255, 255));
        btnNum8.setText("8");
        btnNum8.setAutoscrolls(true);
        btnNum8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum8.setContentAreaFilled(false);
        btnNum8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum8.setFocusPainted(false);
        btnNum8.setVerifyInputWhenFocusTarget(false);
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });

        btnNum9.setBackground(new java.awt.Color(255, 255, 255));
        btnNum9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNum9.setForeground(new java.awt.Color(255, 255, 255));
        btnNum9.setText("9");
        btnNum9.setAutoscrolls(true);
        btnNum9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNum9.setContentAreaFilled(false);
        btnNum9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNum9.setFocusPainted(false);
        btnNum9.setVerifyInputWhenFocusTarget(false);
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });

        btnPorcent.setBackground(new java.awt.Color(255, 255, 255));
        btnPorcent.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPorcent.setForeground(new java.awt.Color(255, 255, 255));
        btnPorcent.setText("%");
        btnPorcent.setAutoscrolls(true);
        btnPorcent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnPorcent.setContentAreaFilled(false);
        btnPorcent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPorcent.setFocusPainted(false);
        btnPorcent.setVerifyInputWhenFocusTarget(false);
        btnPorcent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentActionPerformed(evt);
            }
        });

        btnEleva.setBackground(new java.awt.Color(255, 255, 255));
        btnEleva.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEleva.setForeground(new java.awt.Color(255, 255, 255));
        btnEleva.setText("x^y");
        btnEleva.setAutoscrolls(true);
        btnEleva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEleva.setContentAreaFilled(false);
        btnEleva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEleva.setFocusPainted(false);
        btnEleva.setVerifyInputWhenFocusTarget(false);
        btnEleva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElevaActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(255, 255, 255));
        btnRaiz.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRaiz.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiz.setText("√");
        btnRaiz.setAutoscrolls(true);
        btnRaiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnRaiz.setContentAreaFilled(false);
        btnRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRaiz.setFocusPainted(false);
        btnRaiz.setVerifyInputWhenFocusTarget(false);
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(255, 255, 255));
        btnDiv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("÷");
        btnDiv.setAutoscrolls(true);
        btnDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnDiv.setContentAreaFilled(false);
        btnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDiv.setFocusPainted(false);
        btnDiv.setVerifyInputWhenFocusTarget(false);
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnVezes.setBackground(new java.awt.Color(255, 255, 255));
        btnVezes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVezes.setForeground(new java.awt.Color(255, 255, 255));
        btnVezes.setText("×");
        btnVezes.setAutoscrolls(true);
        btnVezes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnVezes.setContentAreaFilled(false);
        btnVezes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVezes.setFocusPainted(false);
        btnVezes.setVerifyInputWhenFocusTarget(false);
        btnVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVezesActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(255, 255, 255));
        btnMenos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("–");
        btnMenos.setAutoscrolls(true);
        btnMenos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnMenos.setContentAreaFilled(false);
        btnMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenos.setFocusPainted(false);
        btnMenos.setVerifyInputWhenFocusTarget(false);
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnSoma.setBackground(new java.awt.Color(255, 255, 255));
        btnSoma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSoma.setForeground(new java.awt.Color(255, 255, 255));
        btnSoma.setText("+");
        btnSoma.setAutoscrolls(true);
        btnSoma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnSoma.setContentAreaFilled(false);
        btnSoma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSoma.setFocusPainted(false);
        btnSoma.setVerifyInputWhenFocusTarget(false);
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 255, 255));
        btnIgual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.setAutoscrolls(true);
        btnIgual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnIgual.setContentAreaFilled(false);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIgual.setFocusPainted(false);
        btnIgual.setVerifyInputWhenFocusTarget(false);
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnDot.setBackground(new java.awt.Color(255, 255, 255));
        btnDot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDot.setForeground(new java.awt.Color(255, 255, 255));
        btnDot.setText(".");
        btnDot.setAutoscrolls(true);
        btnDot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnDot.setContentAreaFilled(false);
        btnDot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDot.setFocusPainted(false);
        btnDot.setVerifyInputWhenFocusTarget(false);
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnLimpa.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLimpa.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpa.setText("CE");
        btnLimpa.setAutoscrolls(true);
        btnLimpa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnLimpa.setContentAreaFilled(false);
        btnLimpa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLimpa.setFocusPainted(false);
        btnLimpa.setVerifyInputWhenFocusTarget(false);
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPorcent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEleva, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEleva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPorcent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElevaActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText("");
        sinal  = "eleva";
        block();
    }//GEN-LAST:event_btnElevaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        v2 = Double.parseDouble(txtArea.getText());
        if(sinal == "soma"){
            txtArea.setText(String.valueOf(v1 + v2));
        }
        if(sinal == "menos"){
            txtArea.setText(String.valueOf(v1 - v2));
        }
        if(sinal == "vezes"){
            txtArea.setText(String.valueOf(v1 * v2));
        }
        if(sinal == "div"){
            if(v2 == 0){
                JOptionPane.showMessageDialog(null, "Erro!\nO número não pode ser dividido por 0!", "Erro!", JOptionPane.ERROR_MESSAGE);
                reset();
            }else{
                txtArea.setText(String.valueOf(v1 / v2));
            }
        }
        if(sinal == "eleva"){
            txtArea.setText(String.valueOf(Math.pow(v1, v2)));
        }
        if(sinal == "raiz"){
            txtArea.setText(String.valueOf(Math.sqrt(v1)));
        }
        if(sinal == "porcentagem"){
            double percentual = Double.parseDouble(txtArea.getText());
            double resultado = v1 * (percentual / 100);
            txtArea.setText(Double.toString(resultado));
        }
        unblock();
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if(txtArea.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Erro!\nEscolha um número antes do ponto!", "Erro!", JOptionPane.ERROR_MESSAGE);
            txtArea.setText("");
            reset();
        }
        else{
            txtArea.setText(txtArea.getText() + ".");
            btnDot.setEnabled(false);
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        txtArea.setText(txtArea.getText() + "0");
        cont();
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText("");
        sinal  = "soma";
        block();
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText("");
        sinal  = "menos";
        block();
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVezesActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText("");
        sinal  = "vezes";
        block();
    }//GEN-LAST:event_btnVezesActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText("");
        sinal  = "div";
        block();
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText(String.valueOf(Math.sqrt(v1)));
        sinal  = "raiz";
        block();
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        txtArea.setText(txtArea.getText() + 8);
        cont();
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        reset();
        unblock();
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void btnPorcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentActionPerformed
        v1 = Double.parseDouble(txtArea.getText());
        txtArea.setText("");
        sinal  = "porcentagem";
        block();
    }//GEN-LAST:event_btnPorcentActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        txtArea.setText(txtArea.getText() + "9");
        cont();
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        txtArea.setText(txtArea.getText() + "7");
        cont();
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        txtArea.setText(txtArea.getText() + "6");
        cont();
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed
        txtArea.setText(txtArea.getText() + "5");
        cont();
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        txtArea.setText(txtArea.getText() + "4");
        cont();
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        txtArea.setText(txtArea.getText() + "3");
        cont();
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        txtArea.setText(txtArea.getText() + "2");
        cont();
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        txtArea.setText(txtArea.getText() + "1");
        cont();
    }//GEN-LAST:event_btnNum1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEleva;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPorcent;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnVezes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtArea;
    // End of variables declaration//GEN-END:variables

    public void cont(){
        if(txtArea.getText().length() == 12){
            btnNum0.setEnabled(false);
            btnNum1.setEnabled(false);
            btnNum2.setEnabled(false);
            btnNum3.setEnabled(false);
            btnNum4.setEnabled(false);
            btnNum5.setEnabled(false);
            btnNum6.setEnabled(false);
            btnNum7.setEnabled(false);
            btnNum8.setEnabled(false);
            btnNum9.setEnabled(false); 
        }
    }
    public void block(){
        btnDiv.setEnabled(false);
        btnMenos.setEnabled(false);
        btnSoma.setEnabled(false);
        btnVezes.setEnabled(false);
        btnRaiz.setEnabled(false);
        btnEleva.setEnabled(false);
        btnPorcent.setEnabled(false);
    }
    public void unblock(){
        btnDiv.setEnabled(true);
        btnMenos.setEnabled(true);
        btnSoma.setEnabled(true);
        btnVezes.setEnabled(true);
        btnRaiz.setEnabled(true);
        btnEleva.setEnabled(true);
        btnPorcent.setEnabled(true);
    }
    public void reset(){
        btnNum0.setEnabled(true);
        btnNum1.setEnabled(true);
        btnNum2.setEnabled(true);
        btnNum3.setEnabled(true);
        btnNum4.setEnabled(true);
        btnNum5.setEnabled(true);
        btnNum6.setEnabled(true);
        btnNum7.setEnabled(true);
        btnNum8.setEnabled(true);
        btnNum9.setEnabled(true);
        btnDot.setEnabled(true);
        txtArea.setText("");
    }

}
